language: node_js
node_js:
  - 10
branches:
  only:
    - docs
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn --frozen-lockfile --non-interactive
script:
  - yarn build
after_success:
  - cd docs/.vuepress/dist
  - git init
  - git config --global user.name "${U_NAME}"
  - git config --global user.email "${U_EMAIL}"
  - git add -A
  - git commit -m 'deploy'
  - git push --quiet --force "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: docs/.vuepress/dist/*
  skip_cleanup: true
  on:
    tags: true
