name: "master-branch-release auto release"

on:
  push:
    branches:
      - master

jobs:
  pre-release:
    name: "master-branch-release auto release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          title: "docs branch auto development build release."
